version: '3'
services:
  # postgres:
  #   image: postgres:12
  #   environment:
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - DATABASE_URL=sqlite:////code/db.sqlite3
    build: ./
    command: >
      bash -c "./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
